import type { Customer, Inquiry, Product, Reservation } from "@/types/domain";

export const categories = [
  "Vehicles",
  "Motorcycles",
  "Real Estate",
  "Electronics",
  "Furniture",
  "Appliances",
  "Machinery",
  "Equipment",
];

export const products: Product[] = [
  {
    id: "toyota-fortuner-2021",
    sku: "VEH-FOR-2021-001",
    name: "Toyota Fortuner 2.8 V 4x2",
    category: "Vehicles",
    brand: "Toyota",
    model: "Fortuner",
    condition: "Ready To Use, Registered",
    location: "Quezon City",
    branch: "North EDSA",
    status: "Ready",
    price: 1880000,
    acquisitionCost: 1450000,
    quantity: 1,
    availableQuantity: 1,
    reservedQuantity: 0,
    description: "A well-maintained SUV with clean documents, recent PMS, and verified inspection history.",
    imageUrl: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1200&q=80",
    features: ["Verified documents", "Recent PMS", "Financing-ready", "Warranty-ready inspection"],
    specs: { Engine: "2.8L Diesel", Mileage: "42,000 km", Transmission: "Automatic", Color: "Pearl White" },
  },
  {
    id: "yamaha-nmax-2023",
    sku: "MOT-NMX-2023-002",
    name: "Yamaha NMAX ABS",
    category: "Motorcycles",
    brand: "Yamaha",
    model: "NMAX",
    condition: "Functional, Needs Retouch",
    location: "Makati",
    branch: "Makati Central",
    status: "Inspection",
    price: 128000,
    acquisitionCost: 98000,
    quantity: 1,
    availableQuantity: 1,
    reservedQuantity: 0,
    description: "Low-mileage commuter scooter undergoing final cosmetic inspection.",
    imageUrl: "https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=1200&q=80",
    features: ["ABS", "Digital panel", "Urban-ready", "Inspection scheduled"],
    specs: { Engine: "155cc", Mileage: "8,200 km", Transmission: "CVT", Color: "Matte Gray" },
  },
  {
    id: "condo-bgc-studio",
    sku: "REA-BGC-STD-003",
    name: "BGC Studio Condominium",
    category: "Real Estate",
    brand: "Prime Habitat",
    model: "Studio",
    condition: "Ready To Use, Registered",
    location: "Taguig",
    branch: "BGC",
    status: "Reserved",
    price: 4600000,
    acquisitionCost: 3900000,
    quantity: 1,
    availableQuantity: 0,
    reservedQuantity: 1,
    description: "Move-in ready studio near business districts with complete title documents.",
    imageUrl: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
    features: ["Title verified", "Near offices", "Amenities access", "Rental yield ready"],
    specs: { FloorArea: "28 sqm", Bedrooms: "Studio", Turnover: "Ready", Parking: "Optional" },
  },
  {
    id: "macbook-pro-m3",
    sku: "ELE-MBP-M3-004",
    name: "MacBook Pro M3",
    category: "Electronics",
    brand: "Apple",
    model: "MacBook Pro",
    condition: "Functional, Needs Cleaning",
    location: "Cebu City",
    branch: "Cebu",
    status: "Maintenance",
    price: 118000,
    acquisitionCost: 89000,
    quantity: 2,
    availableQuantity: 1,
    reservedQuantity: 1,
    description: "Business-grade laptop with battery diagnostics and charger included.",
    imageUrl: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1200&q=80",
    features: ["Battery checked", "Charger included", "Ready for imaging", "Invoice-ready"],
    specs: { Processor: "Apple M3", Memory: "16 GB", Storage: "512 GB", Display: "14 inch" },
  },
];

export const customers: Customer[] = [
  { id: "cus-001", fullName: "Rafa Santos", email: "rafa@example.com", contactNumber: "+63 917 000 1001", customerType: "Retail", address: "Quezon City" },
  { id: "cus-002", fullName: "Mika Reyes", email: "mika@example.com", contactNumber: "+63 917 000 1002", customerType: "Dealer", address: "Makati" },
  { id: "cus-003", fullName: "Northline Trading", email: "ops@northline.test", contactNumber: "+63 917 000 1003", customerType: "Corporate", address: "Cebu City" },
];

export const inquiries: Inquiry[] = [
  { id: "inq-001", productId: "toyota-fortuner-2021", customerName: "Rafa Santos", email: "rafa@example.com", status: "New", message: "Can I schedule a viewing this weekend?", createdAt: "2026-05-21" },
  { id: "inq-002", productId: "macbook-pro-m3", customerName: "Northline Trading", email: "ops@northline.test", status: "Qualified", message: "Please send bulk pricing for two units.", createdAt: "2026-05-25" },
];

export const reservations: Reservation[] = [
  { id: "res-001", reservationNumber: "RSV-2026-0001", productId: "condo-bgc-studio", customerName: "Mika Reyes", fee: 50000, expiryDate: "2026-06-05", status: "Confirmed" },
  { id: "res-002", reservationNumber: "RSV-2026-0002", productId: "macbook-pro-m3", customerName: "Northline Trading", fee: 10000, expiryDate: "2026-06-01", status: "Pending" },
];
